name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v26
      - name: Building package
      - run: cargo test
      - run: nix build
